### ISSUE TITLE
Update Dev site with updated Main site code

### ISSUE THREAD

**Issue by RK900** [UN-DESA-Modelling/development-site#9]

**Comment by LordDarkula** [comment]
Wait u mean like merge it in?
What about our improvements?

**Comment by RK900** [comment]
The main header on the new site looks like this
![screen shot 2016-09-21 at 4 51 45 pm](https://cloud.githubusercontent.com/assets/16495330/18732937/c09db810-801b-11e6-8ba3-e3bdb2ea0603.png)

**Comment by LordDarkula** [comment]
Ok. I can do t once I'm done studying for Java H
